### ISSUE TITLE
Feature Request: Accessing a dataset via a private url should hide the hierarchy of Dataverses

### ISSUE THREAD

**Issue by zolttoth** [IQSS/dataverse#11085]
**Overview of the Feature Request**
For double-blind reviews, it is a great feature that anonymous private links can be shared with reviewers. In our repository, which is a nationwide institution, the Dataverse hierarchy represents the organizational structure of research institutes, departments, and laboratories. However, since the Dataverse parents of a given dataset are visible through the breadcrumb, the origin of a dataset can be pinpointed, compromising the blindness of the review process.

**What inspired the request?**

A data scholarship program has been started in Hungary, and one of the participants, who was interested in the double-blind feature, informed us that our repository does not fully comply with the requirements for this type of evaluation.

**What existing behavior do you want changed?**

The display of the breadcrumb (the path of a given dataset) should be hidden when accessed via an anonymous private link.

![image](https://github.com/user-attachments/assets/367dec84-50e8-4b2a-998e-7733e9f1dceb)

**Comment by qqmyers** [comment]
It looks like #10961 addresses your issue? That will be in v6.5.

**Comment by pdurbin** [comment]
I'm pretty sure @sekmiller fixed this in 016fc9a1ada93fe8a8578ce2964e5c19ee231320 as part of #10961 which will be part of Dataverse 6.5, shipping soon.

However, the release note doesn't mention this fix. Maybe it should.

@qqmyers jinx.

**Comment by sekmiller** [comment]
Hi @zolttoth, we have addressed this in the soon to be released 6.5 version. Here is what the dataset page will look like first for privileged users, then Preview URL users:
<img width="1177" alt="Screen Shot 2024-12-11 at 1 21 31 PM" src="https://github.com/user-attachments/assets/79c3f4d5-42ce-47be-9b65-751ac67075bd" />
<img width="1172" alt="Screen Shot 2024-12-11 at 1 22 01 PM" src="https://github.com/user-attachments/assets/7067a1bf-1bf0-4b5f-82cf-d057576ade74" />

**Comment by sekmiller** [comment]
@zolttoth note that there are two types of preview url one which also anonymizes some of the metadata. It is only through the uses of the anonymized preview that the Dataverse hierarchy is hidden

**Comment by zolttoth** [comment]
> Hi @zolttoth, you wrote that one of the participants of a data scholarship program in Hungary let you know that your repository does not fully comply with the requirements for this type of evaluation.
> 
> Is there a list of those requirements published someplace that you could point us to? Or are the requirements just more generally that reviewers shouldn't be able to identify the data owners?
> 
> For the changes to the breadcrumbs we made in the PR at #10961, we weren't guided by any formal requirements in particular, I'm wondering if any exist, and the way you wrote "does not fully comply with the requirements" made me wonder if any formal requirements exist that we could reference for improvements in the future.

Unfortunately there are no written formal requirements in this case, just practical considerations. One of the students participating in the program pointed out that in her research field, knowing the reviewed dataset owner institute is more or less the same as knowing who created the actual dataset. We organize the dataverses of the Hungarian research institutes as I described it, and in our Dataverse (we are on 6.1), the breadcrumb makes visible at least the institute, or even a given laboratory. I have missed the https://github.com/IQSS/dataverse/issues/10950 issue, which directly adresses this, and stated to be part of D6.5.

Thank you all, as far as I see, @sekmiller solution will be good for us.

**Comment by jggautier** [comment]
Thanks @zolttoth!

**Comment by thisisbillie** [comment]
Hello! We’ve noticed that this bug still persists, and we’re not sure why it has reappeared after being marked as fixed.

Please see this [anonymous preview URL of my dataset](https://demo.dataverse.org/dataset.xhtml;jsessionid=6d38c0d1090d191a97db5520cb94?persistentId=doi%3A10.70122%2FFK2%2F9AXIAT&version=DRAFT). The name of the parent dataverse, which includes my name, is still visible. While the full hierarchy is no longer displayed, the immediate parent dataverse name continues to appear.

<img width="1218" height="367" alt="Image" src="https://github.com/user-attachments/assets/81cf0bb2-ec11-4443-851d-494832085a14" />





We also observed that this issue does not occur on the [files page](https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/9AXIAT/JJDY8P&version=DRAFT)

<img width="1205" height="360" alt="Image" src="https://github.com/user-attachments/assets/771833bb-cf49-44b7-9ee3-1e89d586b06b" />

**Comment by sekmiller** [comment]
@thisisbillie I took a quick look and I noticed that your dataverse is unpublished. Its name shouldn't be visible regardless, but I'm wondering if that might be why. I will try one in demo and see if there's an effect. (Never mind - it's happening on a newly published dataverse)

**Comment by sekmiller** [comment]
This was broken in a subsequent update to the dataset.xhtml
