### ISSUE TITLE
Deaccession latest published version prevents further edits, deaccession or create draft

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1308]
When a dataset is deaccessioned, I no longer could edit (so as to create a new version).

**Comment by pdurbin** [comment]
This seems like a duplicate of #1267.

**Comment by eaquigley** [comment]
Passing to @kcondon to determine if this is a duplicate of #1267 and can be closed.

**Comment by kcondon** [comment]
@eaquigley  #1267, #1308 and #2363 are related and could be combined but they are separate:
#1267 complains about the missing metadata tab on any deaccessioned version for permitted users, was a requirement in the FRD, apparently.
#1308 complains about not being able to edit and add a draft after deaccessioning
#2363 indicates a problem happens when the latest published version is deccessioned -the edit button disappears so you cannot deaccession other versions afterwards. This is probably the root cause of #1308 so those two could be combined.

**Comment by kcondon** [comment]
I'm adding notes from #2363 to this and changing the title and description to cover the more general case:

Deaccessioning the latest published version (including all) of a dataset results in the edit button not being rendered so that a user cannot create new draft versions of the dataset and cannot deaccession other versions.

**Comment by mheppler** [comment]
eaquigley commented on Apr 29 in issue #3096 (which I am closing in favor of this issue).

> If a user has a published version of a dataset, creates a draft, and then deaccessions the published version, the Edit button for the dataset doesn't appear in the right corner of the page. It still renders within the individual tabs.

![screen shot 2016-04-29 at 10 34 21 am](https://cloud.githubusercontent.com/assets/5922904/14919245/f658c47e-0df5-11e6-991d-87cbe29539e7.png)

**Comment by mheppler** [comment]
Also deaccession related #1221.

**Comment by pdurbin** [comment]
@sekmiller was this fixed by b5b5f31? I'm putting this in Code Review at https://waffle.io/IQSS/dataverse

**Comment by djbrooke** [comment]
Talked over this in standup today. I'll check in with @sekmiller on Monday.

**Comment by pdurbin** [comment]
@sekmiller and I just spoke about how b5b5f31 indeed should be a fix for this issue so he said this issue should go to QA. I associated it with pull request #3408.

**Comment by kcondon** [comment]
This is  still not working -cannot create a draft from a deaccessioned dataset.

**Comment by kcondon** [comment]
OK, works -according to design doc can only create a draft from a published, not deaccessioned version so that implies you cannot create a draft from a completely deaccessioned dataset.
