### ISSUE TITLE
trailing space in versionnote on the datasetversion

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1685]
I'm seeing trailing space in versionnote on the datasetversion like this:

"There is identifiable data in one or more files. "

See also https://github.com/IQSS/dataverse/issues/1221#issuecomment-79067971

Old redmine ticket about this: https://redmine.hmdc.harvard.edu/issues/2994

**Comment by sekmiller** [comment]
This is fixed. (of course any versions that were previously deaccessioned will continue to have trailing spaces in their Version Notes.)

**Comment by posixeleni** [comment]
@kcondon I dont see a whitespace in the UI. How can I test if it is saving whitespaces in the backend?

**Comment by kcondon** [comment]
@posixeleni Try copying the text (swiping with mouse/ selecting) and see whether there is a space.
Seems like reason for deaccession allowed this so you might try that functionality, it also shows up on versions tab?

**Comment by posixeleni** [comment]
@kcondon When I look at the "View Source" HTML I am still seeing a trailing space under Version Notes:

```
<th id="datasetForm:tabView:versionsTable:j_idt924" class="ui-state-default col-sm-2" role="columnheader"><span></span></th></tr></thead><tfoot></tfoot><tbody id="datasetForm:tabView:versionsTable_data" class="ui-datatable-data ui-widget-content"><tr data-ri="0" class="ui-widget-content ui-datatable-even" role="row"><td role="gridcell">
                    <a id="versionLink" href="/dataset.xhtml?persistentId=doi:10.5072/FK2/5ZKDXJ&amp;version=1.0" class="ui-commandlink ui-widget">1.0</a></td><td role="gridcell">
                    Deaccessioned Reason: There is identifiable data in one or more files. </td>
```
Can you please confirm if there is a trailing space in the db? I don't see any in the UI but its hard to tell how its actually stored.

**Comment by posixeleni** [comment]
FYI @kcondon

Checked with @sekmiller in the DB and there is no trailing white space there. The HTML version must pad it.

Works as expected.

Closing.
