### ISSUE TITLE
Edit Dataset: when creating draft by uploading file, save redirect to page that shows published version instead of draft

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2555]
the URL says DRAFT but the page is still published version.

**Comment by landreev** [comment]
Kevin, as you re-test the "wrong file" bug, could you also retest this please?

**Comment by landreev** [comment]
@kcondon
Kevin, it looks like you never gave this ticket back to me. I'm going to steal it, then quickly give it back to you...

**Comment by landreev** [comment]
Please re-test. 
This was a bizarre side effect of the dataset being locked (hence this was only happening on tabular file uploads). From what I'm seeing, this bug has to be present in the current prod. version too. But I don't have time to check now. 
Should be fixed now.

**Comment by kcondon** [comment]
Leonid, this is still happening when I upload a tabular file but does not happen with plain text only. Passing back.

**Comment by landreev** [comment]
Kevin, 
Did you notice how my last update on this ticket came in at 2:47AM? Yep. It's just as sad as it looks - I really was up past 2AM working on that stuff last night. Meaning, I had just committed that fix, at 2:46AM. And it's also looking like dataverse-internal is still running the last night scheduled build, built at 2:00AM. So please run another build and re-test, is what I'm getting at. :)
But do give it back to me again if it's happening still. Though I'm really hoping it shouldn't be.

**Comment by kcondon** [comment]
@landreev 
You are correct. I did test after making a new build but for some reason the build did not deploy correctly. After redeploying the issue is now fixed. 

I did not noticed your check in time. Your level of commitment is commendable but don't burn yourself out!

Thanks, closing.
