### ISSUE TITLE
File Download: Unauthorized error when user attempts to download a public file from a previous dataset version when the file was deleted.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3661]
Reported by a user in production, see RT 246792.

Downloading public files from previously published dataset versions is allowed and generally works. However, if the file was deleted at some point the user see a not authorized error when trying to download that file from a version where it exists.

Not Authorized - You are not authorized to view this page. If you believe this is an error, please contact Dataverse Support for assistance.

**Comment by shlake** [comment]
We just encountered this at UVa. Ex:  Dataset V1 had file IMDB.sql. Then that file was deleted and IMDBV2.sql was uploaded - published as Dataset V2. 

As non-file owner, I  can see the old filenames in the 1.0 link Versions:
https://dataverse.lib.virginia.edu/dataset.xhtml?persistentId=doi:10.18130/V3/KEVCF8&version=1.0

then get 404 error when clicking on the filename (1st one in the list):
https://dataverse.lib.virginia.edu/file.xhtml?fileId=1167&version=RELEASED&version=.0

BUT I think the problem here is the URL (on the link) is incorrect. This URL works:
https://dataverse.lib.virginia.edu/file.xhtml?fileId=1167&version=1.0

BUT then I still get a 403 error when clicking the download button. 

Logged in as the "owner"/depositor, I can download the file.

So what should the behavior be?

**Comment by djbrooke** [comment]
Hey @shlake, I think the URL formatting issue is #4214, which we fixed up in 4.8.2. We should definitely improve the messaging here, though.

**Comment by pdurbin** [comment]
We should never see `version=.0` in the URL for a file or dataset page. Very strange. What does `.0` even mean as a version number?

**Comment by scolapasta** [comment]
@shlake , discussed with @djbrooke and confirmed that $4214 is not related.

The URLs definitely are wrong (notice that they also say version=RELEASED) and I noticed that wrong format was true for all the files on that dataset. 

Would you mind opening that up as a separate issue? (and this can remain for the 403)

**Comment by scolapasta** [comment]
One more note, which I'll add to the new issue once created:
 I'm guessing it's first getting the version=RELEASED and since it was deleted, that's why you get the 404. i.e. the version =.0 is ignored.

**Comment by LauraHuisintveld** [comment]
We at DANS now encounter the same error that @shlake reported in November. 
When you delete files from a dataset, and click publish to create a new version, the files in the older version are not downloadable any more and URL's seem wrong. (We are using version 4.8.6)

I assume that no separate issue has been created in the mean time, because I do not see it linked here. Is that because a solution has been found, or is it still open and should I create an issue for this?

**Comment by pdurbin** [comment]
@LauraHuisintveld how do you feel about trying to reproduce the download problem on https://demo.dataverse.org which is running 4.9.1?

(Also, the wrong URLs were fixed in #4308 in version 4.9.)

**Comment by pdurbin** [comment]
@shlake thanks. I witnessed this bug myself yesterday when working on a fix for #4822 so this is still a bug as of 4073e2e in the "develop" branch.

**Comment by LauraHuisintveld** [comment]
Thanks for the info @shlake  and @pdurbin . I also tried it myself on the Harvard demo site (https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/XTBCX1) and I was able to download files that were deleted higher versions. Seems like the fix for the wrong URL's is the solution? (https://github.com/IQSS/dataverse/issues/4308) 

@pdurbin: the bug you witnessed yesterday, was this another (related) one? Or am I wrong in assuming that #4308 solved it all?

**Comment by pdurbin** [comment]
@LauraHuisintveld hi, when I go to https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/XTBCX1 I get an "XML Parsing Error: not well-formed" in Firefox...

<img width="1166" alt="screen shot 2018-07-20 at 7 52 48 am" src="https://user-images.githubusercontent.com/21006/43001139-2114aa94-8bf2-11e8-8453-a8c26235d264.png">

... and a "This page contains the following errors: error on line 250 at column 218: AttValue: " or ' expected" error in Chrome...

![screen shot 2018-07-20 at 7 53 05 am](https://user-images.githubusercontent.com/21006/43001138-2106d248-8bf2-11e8-9487-bb6f7b007fee.png)

... so I'm not sure how you can download any files from that "doi:10.5072/FK2/XTBCX1" dataset.

It was this issue (#3661) that I was able to reproduce the other day while working on a fix for #4822 which is now in QA.

In backlog grooming on Wednesday we discussed this issue (#3661) and gave it a size estimate of "3". This issue isn't in the current sprint but if you look at https://waffle.io/IQSS/dataverse you can see that as of this writing it's fairly high up in the backlog:


<img width="2128" alt="screen shot 2018-07-20 at 7 47 18 am" src="https://user-images.githubusercontent.com/21006/43001140-212d621e-8bf2-11e8-9b92-3b42d4728782.png">

**Comment by LauraHuisintveld** [comment]
Thanks @pdurbin , you are right, the error is still there. I was able to download the files, but that was while I was logged in. Good to know it is on the top end of the backlog.

**Comment by benjamin-martinez** [comment]
For clarification, what should a non-authorized/non-owner user see when they try to download a file from an older version that has since been deleted in later versions?

**Comment by landreev** [comment]
@sekmiller 
I vote for removing all the old 2015 comments next to that code fragment. They are more confusing than useful at this point. 

I can see why the code that was in there was not doing the right thing (it insisted that the file must be in the *latest* published version). Again, I would just remove that old, currently commented-out code.

Relying on DatastVersion.isPublished() is ok, yes. 
It definitely fixes the issue at hand (the file deleted from the current published version, but still existing in another published version...)
But have you specifically retested the case where a file that exists in an older published version then gets *restricted* in the later published version? Looking at the code, it looks like it should be doing the right thing (download denied without special permissions). But I would just re-test this specifically, if hasn't been yet.

**Comment by sekmiller** [comment]
Pursuant to Leonid's question I tested the following scenario:

A given data file in:
Version 3 - Deleted
Version 2 - Restricted
Version 1 - Public

The file download API gives an unauthorized message. That is the expected behavior and I think it is correct. Passing to QA.

**Comment by djbrooke** [comment]
Ping @shlake and @LauraHuisintveld - this has been merged and will be included in the next Dataverse release.
