### ISSUE TITLE
As user with administrative responsibility for a dataset, I want to receive a notification when that dataset enters review 

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4143]
Originally noticed during #3998, but more related to "submit for review" workflow.

The context is a dataverse for a research group, where one user (the primary investigator) has administrative/scientific responsibility for datasets for their group, but does not have the ability to publish directly because the datasets need to be reviewed by someone outside the group.  The PI should be notified when a dataset is submitted for review by other users in this dataverse; in particular, so they have the opportunity notify the curator that it's premature to publish the dataset.

One approach suggested by @scolapasta (which is probably preferable to the initial idea of "send the notification to all the dataverse contact emails"): add a notification that's sent to all users with `editor` / `Contributor` permission on the dataset.  The PI can be configured to have `editor` permission on all datasets from their dataverse.

There was also some discussion of a "remove from review" permission / action (which don't yet exist); this would let users change a dataset from "in-review" to "draft" prior to publication (and might intersect with adding a "reviewed" state for datasets).

**Comment by djbrooke** [comment]
We discussed this in backlog grooming today. Notes:

- We won't necessarily create a new role for this
- We could notify all who have edit and publish permissions on the dataset
- We should be careful about the amount of notifications that we are generating. This is covered in a separate issue (?)

**Comment by pdurbin** [comment]
I thought what I heard is that we were estimating sending notifications to people have `ManageDatasetPermissions` on the dataset: https://github.com/IQSS/dataverse/blob/v4.8.2/src/main/java/edu/harvard/iq/dataverse/authorization/Permission.java#L45 . This is fairly straightforward.

**Comment by scolapasta** [comment]
Nope it's for edit dataset and publish dataset (the later already exists). At least that is the approach I had suggested.

**Comment by pdurbin** [comment]
Using `EditDataset` and `PublishDataset` permissions is straightforward too. Thanks.

**Comment by matthew-a-dunlap** [comment]
FWIW I have started on this and I think have working code but am running into a failing test that is confusing me. Will continue tomorrow.

**Comment by djbrooke** [comment]
I was happy to estimate this but I wanted to discuss it a bit more before pulling it into dev, because I'm a little concerned about this getting spammy. 

@jggautier and @dlmurphy, this may be a good opportunity to query prod and use some analytics to determine how many additional folks would receive emails if we implemented this. I understand the @pameyer use case, but his workflow is not typical (no offense, Pete :)).

**Comment by jggautier** [comment]
Sending submit for review notifications to people with editDataset permissions means that Dataverse will start sending notifications to everyone with contributor roles at the dataverse and dataset level.
- 95 people with contributor roles in dataverses in Harvard Dataverse would start getting notifications when others submit datasets for review in their dataverses.¹

- When someone submits a dataset for review, she'll also start getting notifications. For October and November², about 116 people have submitted datasets for review in Harvard Dataverse. That's about half the number of people (234) who've published datasets (including republishing new versions) in those two months.

We know the dataverses in Harvard Dataverse with the greatest number of people assigned contributor roles. Might be helpful to ask those dataverse admins how this change might affect their workflows.

¹ There are 125 contributor roles in dataverses in Harvard Dataverse (as of Dec. 5, 2017), which belong to 109 user accounts, which probably belong to about 95 people. (This includes people in explicit groups that are assigned contributor roles in dataverses.) 

² Dataverse's database started logging submit for reviews in October 2017.

**Comment by jggautier** [comment]
> @jggautier and @dlmurphy, this may be a good opportunity to query prod and use some analytics to determine how many additional folks would receive emails if we implemented this. I understand the @pameyer use case, but his workflow is not typical (no offense, Pete :)).

@sbarbosadataverse noted during the 2018 Community Meeting that someone asked if the depositor could choose the people that would receive the notification. I wonder if the depositor could choose from the list of people with edit access to that dataset, and if this would help prevent too many email notifications from going out.

**Comment by sbarbosadataverse** [comment]
The desired functionality is:

1-only "administrators" get notified when a dataset has been submitted for review or, not "curators"
2-admins can select those from their "admin" list that should be notified (this would take more work)

**Comment by sbarbosadataverse** [comment]
@TaniaSchlatter not sure this is still an issue? Admins do get notified. Should the issue be "only admins" should be notified? If the submit workflow is notifying curators as well?

**Comment by TaniaSchlatter** [comment]
@pameyer can you confirm that this is still an issue?

**Comment by pameyer** [comment]
@TaniaSchlatter I'll check; but my first assumption is that if @sbarbosadataverse doesn't think it's still an issue than it probably isn't.
