### ISSUE TITLE
Accessibility - Subject selection in "Add Dataset" can't be accessed via keyboard tabbing

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#4423]
Tested in both Scholars Portal DV (4.7.1) and Harvard DV (4.8.4) in Firefox on Mac.

When trying to access the subject selection checkboxes while adding a new dataset, they can't be reached via keyboard navigation. ([e.g. here](https://dataverse.harvard.edu/dataset.xhtml?ownerId=1))

Here's a screenshot of the area I'm referring to - tabbing skips over these checkboxes entirely. This is especially problematic because these are required fields.

![screen shot 2018-01-19 at 9 19 21 am](https://user-images.githubusercontent.com/6903515/35154891-f290962e-fcf9-11e7-93d2-94692cc117c0.png)

Let me know if any additional information is needed!

**Comment by mheppler** [comment]
Thank you for catching this and creating an issue @kaitlinnewson.

Looking into this quickly, it appears that this is a [known issue with the `selectManyCheckbox` component in PrimeFaces 5](https://github.com/primefaces/primefaces/issues/1047). It appears to have been fixed in PrimeFaces 6, which we have already an issue for, UI - Primefaces 6 Upgrade #4220.

**Comment by kaitlinnewson** [comment]
That's great, it looks like this will fix a lot of accessibility issues!

**Comment by pdurbin** [comment]
@mheppler heads up that I just tried tabbing through "Subject" on https://demo.dataverse.org running Dataverse 4.9.4 and this accessibility issue still seems to exist (I'm using Firefox) even though we upgraded to Primefaces 6.2 in Dataverse 4.9.2. Bummer. Others are encouraged to re-test as well.

**Comment by mheppler** [comment]
While working on #5717 I had run into this issue. After a little digging, it was discovered that this is an issue with the Firefox browser on Mac OS. From an [answer on Stack Overflow](https://stackoverflow.com/a/11713537):

> Ok, somebody explained this to me. It's a Mac problem. Mozilla is being true to operating system settings in Mac OS.
>
>There are two distinct ways around this on the user side. Both seem to work:
>
>    In System Preferences → Keyboard, in the Shortcuts pane, check the “all controls” radio at the bottom.
>
>    In Firefox, type "about:config" in the URL bar. There is no accessibility.tabfocus preference on the mac, so you'll have to make one. Right click in the window, create a new "integer" pref, and set it to 7.
>
>Neither of these are terribly obvious. Also, neither of these are a server-side solution for developers, which is frustrating.

This would explain why the subject checkboxes can be focused in Chrome and Safari on Mac. Also worth exploring are the improvements outlined in [PrimeFaces 7](https://www.primefaces.org/primefaces-7-0-final-released/) -- "various components have been enhanced for accessibility related to keyboard support and screen readers".

**Comment by kaitlinnewson** [comment]
@mheppler I re-tested in Firefox, Chrome (75.0.3770.100), and Safari (12.1.1) on Mac in Harvard's instance (4.14) and am still seeing the same issue. I also already have 'All controls' enabled in my System preferences.

**Comment by mheppler** [comment]
@kaitlinnewson in our 4.15 there were some accessibility improvement (#5717) made to various forms across the UI, and I believe those fixed the problem of highlighting and selecting the checkboxes in the Subject metadata form component.

You can test for yourself in demo (v. 4.17 build 1450-51739f6) right now. (See screenshot.) I was able to confirm this functionality in both Firefox and Safari.

![Screen Shot 2019-11-20 at 1 21 27 PM](https://user-images.githubusercontent.com/687227/69266181-ae929d00-0b98-11ea-9e40-e4a39b1732cd.png)

I am going to go ahead and close this issue, as fixed by #5717 as of our 4.15 release.

Also of note related to the Subject metadata form component, we are currently in the process of fixing the bug you reported in _Subjects disappear when clicked in metadata editing #6339_. The solution there was to ultimately remove the PrimeFaces selectManyCheckbox checkbox list component in a scrolling container. We will be reviewing the accessibility of that new component to make sure it remains accessible.
