### ISSUE TITLE
Double Rainbows! File tag list is doubled and cannot add new custom tag using batch edit if a single tabular file exists in dataset,

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4976]
Reported by in house curation services, see RT 265898
When a dataset has at least one tabular file, the tags feature does not work properly:
when editing tags in batch edit mode (select file from dataset page, choose edit, tags)
non tabular tags list is doubled (repeated) and you cannot save a new custom tag.
This works if done from the edit file metadata page/ non batch mode, and works when no tabular files present.

**Comment by kcondon** [comment]
Fixed by broken gb issue #4838

**Comment by dliburd** [comment]
On Friday, I was meeting with Danny when he noticed that there continues to be duplicate tags listed when applying tags to files on Dataverse. He thought this bug was fixed in the latest release to the issue persists. I was working on a MRA study (https://hdl.handle.net/1902.1/00640) when he noticed the duplicates.

**Comment by mheppler** [comment]
@dliburd @kcondon Pretty sure this fix hasn't been released yet (it's only 6 days old), so you will continue to see this issue on Harvard Dataverse until we upgrade it with our next 4.9.3 (?) release -- whenever that may be cut.

**Comment by kcondon** [comment]
True

**Comment by djbrooke** [comment]
@mheppler @kcondon  - I thought that as well, but I believe we patched prod with #4838, which contains this fix. I'm happy to be wrong here and re-close this if someone has correct info.

**Comment by kcondon** [comment]
OK, just checked with Leonid and you're right, that fix was deployed as a patch. Any chance his/your browser had been opened since before the patch? I can retest in prod but testing in test indicated it as fixed by this patch.

**Comment by djbrooke** [comment]
@dliburd - can you please provide the specific steps to reproduce this one?

**Comment by djbrooke** [comment]
walked by the office and saw @dliburd and @kcondon already talking. Thank you!
