### ISSUE TITLE
4.8.6 update script broken for no shoulder case

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5057]
I think the following lines in upgrade_v4.8.6_to_v4.9.0.sql below is incorrectly setting authority and shoulder for the case of no shoulder e.g. when the 4.8.6 authority ='10.5072' - affecting a couple of instances

--Add new setting into content for shoulder
INSERT INTO setting(name, content)
VALUES (':Shoulder', (SELECT substring(content, strpos(content,'/')+1) || '/' from setting  where name = ':Authority'));

 --strip shoulder from authority setting
 UPDATE setting
 SET content=(SELECT substring(content from 0 for strpos(content,'/'))
 FROM setting
 WHERE name=':Authority' and strpos(content,'/')>0) where name=':Authority';

The following queries should only create a :Shoulder setting if needed and only adjust authority if it includes a shoulder:

--Add new setting into content for shoulder if needed

INSERT INTO setting(name, content)
SELECT ':Shoulder', substring(content, strpos(content,'/')+1) || '/' from setting  where name = ':Authority' and strpos(content,'/')>0;

 --strip shoulder from authority setting if the shoulder exists
UPDATE setting
SET content= case when (strpos(content,'/')>0) then substring(content from 0 for strpos(content,'/'))
else content end where name=':Authority';

Since this is a script related to the 4.9.0 version, I'm not sure whether this should be a PR to 4.9.0 or perhaps something you just post in an update on the release page?

**Comment by qqmyers** [comment]
Relates to #4923 - it would stop 4923 from occurring but won't fix things if DOIs have been minted after using the old script.

**Comment by qqmyers** [comment]
FWIW: https://github.com/QualitativeDataRepository/dataverse/commit/b5334eb61c019f7891239b61c1a899c1c7283572

**Comment by pdurbin** [comment]
It sounds like https://groups.google.com/d/msg/dataverse-community/Ivh2137nESc/6-kiMU7GBwAJ might be an example of an installation run by @oodu suffering from this problem. Thanks for all the details above, @qqmyers

**Comment by pdurbin** [comment]
@bricas thanks for leaving a comment here and for hanging in there with the troubleshooting at http://irclog.iq.harvard.edu/dataverse/2019-01-16#i_84863

#4923 is related. I wonder how many more installations are out there that don't use a "shoulder" and have yet to upgrade. Hopefully not too many.

**Comment by PaulBoon** [comment]
We at DANS have been bitten as well. 

After upgrading our 4.8.6 based fork my handles could not be registered because the :Authority setting was gone. 
When I added it ('12345' on our dev server) the handles register again, but now contain  the prefix twice; example citation:

> `Admin, Dataverse, 2019, "test6", https://hdl.handle.net/12345/12345/FHVKWR, DataverseNL, DRAFT VERSION `

where the prefix is '12345' and used to be in the :Authority setting But now the :Shoulder is '12345/' and all identifiers are prefixed with this shoulder and when registering we use the :Authority, which is then also prefixed. 

The problem is fixed by not only setting the :Authority back to '12345' but also unsetting the :Shoulder setting. 

This problem is caused by the sql upgrade script upgrade_v4.8.6_to_v4.9.0.sql, which does not work correctly in case we have no '/' in the :Authority setting. 
My guess is that if the :Authority was 'A/B' the result should be that 'B/' becomes the :Shoulder and 'A' the  :Authority, but if it is just 'A' I see that we have 'A/' for the :Shoulder and no :Authority. 
The solution would be to fix the sql that is doing this. 

https://github.com/IQSS/dataverse/releases/download/v4.9/upgrade_v4.8.6_to_v4.9.0.sql

**Comment by pdurbin** [comment]
@PaulBoon sorry to hear this bug bit you. 😞 Are you interested in trying the "handle no shoulder case" bug fix that @qqmyers mentioned above? It's at https://github.com/QualitativeDataRepository/dataverse/commit/b5334eb61c019f7891239b61c1a899c1c7283572

**Comment by PaulBoon** [comment]
Why isn't the file updated with the fixes from @qqmyers, edit the v4.9 release, delete this upgrade_v4.8.6_to_v4.9.0.sql file and then upload the improved one. 
Otherwise everyone using it has a potential upgrade problem.

**Comment by qqmyers** [comment]
@PaulBoon - Thanks - I updated the comment above to include the missing 'UPDATE setting' line you noticed. Note that the commit is against a file that no longer exists - the name has changes to upgrade_v4.8.6_to_4.9,sql

**Comment by pdurbin** [comment]
Thanks @PaulBoon and @qqmyers ! The only reason a SQL script with the fixes above hasn't been made available is that this issue hasn't been prioritized. Are either of you interested in making a pull request? Once there's a pull request I'm happy to drag this issue over to code review at https://waffle.io/IQSS/dataverse . From the perspective of that kanban board, this issue is still in the "inbox".

**Comment by qqmyers** [comment]
@pdurbin , @PaulBoon - PR created (a new commit, hopefully no cut/paste errors).

**Comment by pdurbin** [comment]
@qqmyers thanks! I moved it to code review.
