### ISSUE TITLE
File upload: large file uploads should show up in the file table after each ingest, before save

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5434]
See attached screen shot.
When uploading large files, after the blue bar is complete, files are not listed below where is says "file you upload will appear here"

<img width="1959" alt="screen shot 2019-01-04 at 1 01 26 pm" src="https://user-images.githubusercontent.com/8322346/50703071-e9dbba00-1020-11e9-87ea-d8e43e9582e1.png">

**Comment by pdurbin** [comment]
I just wanted to note that Harvard Dataverse is running 4.9.4 at the moment.

**Comment by pdurbin** [comment]
@sbarbosadataverse is this any better now that Harvard Dataverse is running 4.10.1?

The reason I thought to circle back to this issue is that @Mahsanas just reported a very similar issue with 4.9.4 in IRC:

"Hi, We seem to have a problem when uploading files larger than 100 MB. The upload progress bar completes, but the files does not move from the top widnow to the bottom winodw (where the uploaded files usually appear)."

Details at http://irclog.iq.harvard.edu/dataverse/2019-01-09#i_84292 and kudos to @pameyer for helping to troubleshoot.

**Comment by qqmyers** [comment]
Just saw the chat log - PR #4522 started catching errors such as proxy timeouts that caused this, but I recently discovered that the changes to add provenance upload broke that error checking code. I'm working on a PR to fix it again. In the meantime, if there's a silent error, check for things like a 502 Proxy timeout error or other network error (visible in the browser log) - these cause a problem that the Dataverse server is not aware of and hence can't report.

**Comment by qqmyers** [comment]
Just created PR #5466 - I think it is complete, but I fixed this as part of another branch, so it's possible I've missed some code. If anyone sees issues, let me know.

**Comment by Mahsanas** [comment]
This was very helpful. I was able to look at the logs on my browser and see
that it is a 400 error (Bad Request) when uploading large files.
It might be coming from my Apache settings. If I remember correctly we did
not have any issue uploading large files before fronting glassfish with
Apache.

**Comment by mheppler** [comment]
Suggested to @qqmyers that his PR gets connect to a new issue, specific to the error logging fix, so that this issue reporting large file upload problems can remain open, and continue to be diagnosed.

Confirmed with @sbarbosadataverse that she was still seeing these issues on Wed Jan 9, the day after 4.10.1 was deployed to production.

With @landreev returning to the office tomorrow, I am going to check in with him to see if he has any ideas.

Shout out's to @matthew-a-dunlap, @sekmiller, @pameyer and @scolapasta for code review feedback, process input and file upload background. :air-horn-sound:

**Comment by Mahsanas** [comment]
A quick update that I found and fixed the large file upload problem for our
dataverse instance.
For us, it was connected to the mod_JK HTTP settings (maxpostsize) on
glassfish.
I disabled the maxpostszie limit (set it to -1) and the problem was solved.
