### ISSUE TITLE
Create a javascript for the frontend that supports Fundref

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9150]
Definition of Done:
- [ ] front end is created
- [ ] Code, javascript and a test metadatablock in the other repo

(i.e. not production )

**Comment by mreekie** [comment]
Jim suggests the following as a rough breakdown on a backlog for the backend:
identify the official source of the vocabulary,
discover whether there are services available via API to query them,
discover if there are existing vocabulary browsers that can serve as examples or provide source code,
identify a viable identifier for the terms in the vocabulary,
create a simple example browser to demonstrate edit/display in Dataverse,
investigation of whether the vocabularies are internationalized and if so, how the translations can be accessed, decide which field(s) in Dataverse they should be applied to, etc.

**Comment by mreekie** [comment]
priority discussion with Stefano;
- Size this.
- If it's not overly large, get it to the top of the sprint ready backlog

**Comment by mreekie** [comment]
Top priority for upcoming sprint

**Comment by mreekie** [comment]
sizing:
For this task someone will need to look at example java scripts and the funding field that we need to populate. e.g. is it a single field or does it have child fields, etc. From there look at our sample scripts. Then look at the crossref fundref API and figure out how to use it from javascript
No one has done this before
We would probably be using the external vocab repo for sample script.

Size as a 33.
This is work that if done repeatedly this would become smaller - like a 10, but here we don't have the experience..

**Comment by jggautier** [comment]
@pdurbin, for usability testing the workflow with the javascript, would it be possible to either create a test server or to use Demo Dataverse? If we need to add new fields or think it would be better to, would it be easier to create a test server, like spinning something up on AWS?

To figure out who best to contact for testing, I'm reviewing metadata in the Harvard repository to find users who most often add funding information.

While I'm doing that it makes sense to look at the extent of https://github.com/IQSS/dataverse/issues/4859 (how many users enter funding metadata in both fields). Might be possible to learn more about that, too.

**Comment by pdurbin** [comment]
@jggautier sure, a demo server sounds good. Here's a quick dump from the first entry (NFS) from the first API endpoint listed at https://www.fundref.org/documentation/funder-registry/funder-data-via-the-api/

```
curl -s https://api.crossref.org/funders | jq '.message.items[0]'
{
  "id": "100000001",
  "location": "United States",
  "name": "National Science Foundation",
  "alt-names": [
    "U.S. National Science Foundation",
    "USA NSF",
    "USNSF",
    "NSF",
    "US National Science Foundation",
    "US NSF"
  ],
  "uri": "http://dx.doi.org/10.13039/100000001",
  "replaces": [],
  "replaced-by": [],
  "tokens": [
    "national",
    "science",
    "foundation",
    "us",
    "national",
    "science",
    "foundation",
    "usa",
    "nsf",
    "usnsf",
    "nsf",
    "us",
    "national",
    "science",
    "foundation",
    "us",
    "nsf"
  ]
}
```

That DOI for NSF ( http://dx.doi.org/10.13039/100000001 ) redirects to the HTTPS version ( https://dx.doi.org/10.13039/100000001 ) which redirects to http://data.crossref.org/fundingdata/funder/10.13039/100000001 where even more info is shown:

```
{
    "country": {"resource": "http://sws.geonames.org/6252001/"},
    "address": {"postalAddress": {"addressCountry": "usa"}},
    "inScheme": {"resource": "http://data.crossref.org/fundingdata/vocabulary"},
    "created": "2009-07-06T18:53:11.0",
    "prefLabel": {"Label": {
        "literalForm": {
            "lang": "en",
            "content": "National Science Foundation"
        },
        "about": "http://data.crossref.org/fundingdata/vocabulary/Label-36515"
    }},
    "narrower": [
        {"resource": "http://dx.doi.org/10.13039/100000076"},
        {"resource": "http://dx.doi.org/10.13039/100000083"},
        {"resource": "http://dx.doi.org/10.13039/100000081"},
        {"resource": "http://dx.doi.org/10.13039/100000084"},
        {"resource": "http://dx.doi.org/10.13039/100000085"},
        {"resource": "http://dx.doi.org/10.13039/100000086"},
        {"resource": "http://dx.doi.org/10.13039/100000088"},
        {"resource": "http://dx.doi.org/10.13039/100005447"},
        {"resource": "http://dx.doi.org/10.13039/100005441"},
        {"resource": "http://dx.doi.org/10.13039/100000179"},
        {"resource": "http://dx.doi.org/10.13039/100005716"},
        {"resource": "http://dx.doi.org/10.13039/100010608"},
        {"resource": "http://dx.doi.org/10.13039/100014072"},
        {"resource": "http://dx.doi.org/10.13039/100014073"},
        {"resource": "http://dx.doi.org/10.13039/100014411"},
        {"resource": "http://dx.doi.org/10.13039/100014591"},
        {"resource": "http://dx.doi.org/10.13039/100015815"},
        {"resource": "http://dx.doi.org/10.13039/100020427"},
        {"resource": "http://dx.doi.org/10.13039/100020475"}
    ],
    "altLabel": [
        {"Label": {
            "literalForm": {
                "lang": "en",
                "content": "US National Science Foundation"
            },
            "about": "http://data.crossref.org/fundingdata/vocabulary/Label-63344"
        }},
        {"Label": {
            "literalForm": {
                "lang": "en",
                "content": "U.S. National Science Foundation"
            },
            "about": "http://data.crossref.org/fundingdata/vocabulary/Label-89014"
        }},
        {"Label": {
            "literalForm": {
                "lang": "en",
                "content": "NSF"
            },
            "usageFlag": {"resource": "http://data.crossref.org/fundingdata/vocabulary/acronym"},
            "about": "http://data.crossref.org/fundingdata/vocabulary/Label-24515131"
        }},
        {"Label": {
            "literalForm": {
                "lang": "en",
                "content": "US NSF"
            },
            "usageFlag": {"resource": "http://data.crossref.org/fundingdata/vocabulary/acronym"},
            "about": "http://data.crossref.org/fundingdata/vocabulary/Label-952985"
        }},
        {"Label": {
            "literalForm": {
                "lang": "en",
                "content": "USA NSF"
            },
            "usageFlag": {"resource": "http://data.crossref.org/fundingdata/vocabulary/acronym"},
            "about": "http://data.crossref.org/fundingdata/vocabulary/Label-20677577"
        }},
        {"Label": {
            "literalForm": {
                "lang": "en",
                "content": "USNSF"
            },
            "usageFlag": {"resource": "http://data.crossref.org/fundingdata/vocabulary/acronym"},
            "about": "http://data.crossref.org/fundingdata/vocabulary/Label-3698180"
        }}
    ],
    "fundingBodyType": "gov",
    "fundingBodySubType": "National government",
    "modified": "2022-11-02T19:22:47.0",
    "id": "https://doi.org/10.13039/100000001",
    "state": {"resource": "http://sws.geonames.org/6254928/"},
    "region": "Americas"
}
```

Given the existing fields...

![Screen Shot 2023-01-18 at 3 37 29 PM](https://user-images.githubusercontent.com/21006/213289487-54cfd9f3-c37b-40e1-ad9a-e6f618286acb.png)

... I assume we'd fill them in like this:

![Screen Shot 2023-01-18 at 3 39 35 PM](https://user-images.githubusercontent.com/21006/213289746-cdbb2fb6-34c5-4fd2-907e-161b96885e49.png)

That is:

  "name": "National Science Foundation",
  "id": "100000001",

Or is the uri (from the first JSON, to avoid making the second call) better?

![Screen Shot 2023-01-18 at 3 40 59 PM](https://user-images.githubusercontent.com/21006/213290080-12299c7e-c377-48c5-81f7-1e6c7cfc74dd.png)

That is:

  "name": "National Science Foundation",
  "uri": "http://dx.doi.org/10.13039/100000001",

I realize this is http rather than https, but that's ok. Like I said above, it redirects.

**Comment by qqmyers** [comment]
+1 for URI -  100000001 could be anyone's numbering system. The JavaScript in view mode can hide the URI form if desired - either just showing the number or even showing just one field with [National Science Foundation](https://doi.org/10.13039/100000001) - as a link - so what's best to display can be a separate issue from what to store.

(Sadly while all the variants of http(s)://(dx.)doi.org/ all redirect to the right place, they do give you four variants of the URI to use as the identifier. Using what they say (unless DataCite has a preference?) is probably best practice although https://doi.org/10.13039/100000001 is the most modern at this point.)

**Comment by pdurbin** [comment]
Wait, the old name for the field (from #4859) was "Grant ID")...

![46164147-3615a200-c25b-11e8-8cb8-c4a288da51ae](https://user-images.githubusercontent.com/21006/213446356-1a988db5-7a76-403e-9e5e-82c3c38bb2b9.png)

... I think the popup text confused me. I need to dig more into these fields, obviously.

**Comment by jggautier** [comment]
Great catch and sorry for the confusion!

The second child field, Identifier, should be the identifier of the funding, not of the funder. The tooltip used to be "The grant or contract number of the **project** that  sponsored the effort." "Project" was changed to "agency" when we tried to improve the tooltips last year.

Could we fix the tooltips in this GitHub issue? Or I could open a new issue.

**Comment by pdurbin** [comment]
@jggautier sure, a new issue sounds fine. Honestly, simply changing "of" to "from" would help me a lot. Like this:

`-datasetfieldtype.grantNumberValue.description=The grant identifier or contract identifier of the agency that provided financial support for the Dataset`
`+datasetfieldtype.grantNumberValue.description=The grant identifier or contract identifier from the agency that provided financial support for the Dataset`

**Comment by jggautier** [comment]
Makes sense to me. I'll open an issue about it.

About this issue, from https://github.com/IQSS/dataverse/issues/7285#issuecomment-1396234818, it sounds like I should wait to hear from @mreekie about finding a time to discuss, and maybe you could join us? I think the scope might change once we're all the same page about what we expect depositors to enter in the current fields.

In the meantime it might be helpful to know that when depositors have filled the second child field, Identifier, it looks like it's always a funding ID, never the ID of the funder. So there's no evidence yet of anyone else misinterpreting that field, although I've only looked at datasets from research funded by the NIH. Although I still agree that changing "of" to "from" seems clearer to me, too.

I'll share the spreadsheet of metadata that shows what depositors are filling in the funding fields in a bit.

**Comment by jggautier** [comment]
Just to keep things clear and updated, when someone chooses a funder from the Funding Information Agency dropdown list that this javascript produces from the CrossRef API, the funder's identifier should not go in the Funding Information Identifier field. Instead, the Funding Information Identifier field (the second child field) is for the award ID.

- Where should the funder's identifier go?
  - We could create a new field and have that be populated with the funder's identifier. Seeing the funder ID of the funder name they chose might give depositors more verification that they've chosen the right funder from the suggestions. But if depositors don't choose from the suggested list, can they fill in their own funder name and funder identifier in the newly created funder identifier field?

- Is it possible to also get suggested award IDs from Crossref's APIs to help people fill in the Funding Information Identifier? Would it be the same "javascript" providing suggestions for both fields? Or one "javascript" for each field? I read [the white paper](https://docs.google.com/document/d/17XfX83z23UkUy2v0S0cmHdShjvgB8Q9t5OtcNStZaAI) and [what Mike wrote in an earlier comment](https://github.com/IQSS/dataverse/issues/9150#issuecomment-1307752198) about Jim's suggestions, but this isn't clear to me.

**Comment by mreekie** [comment]
waiting right now on some input from the ROR work.

**Comment by jggautier** [comment]
I think it's important to publicize the use-cases that this work will support. This will help with evaluation/testing.

The NIH GREI group is interested in helping funders find the data produced by the research they've funded, specifically NIH funded research. This is one of the use-cases they want each repository to support. And this javascript supports that goal by letting Dataverse repositories more consistently record funding agency names and record persistent identifiers.

Because a lot of the funding agency metadata in the Harvard Dataverse looks like this today...

<img width="674" alt="Screen Shot 2023-01-23 at 3 37 18 PM" src="https://user-images.githubusercontent.com/18374574/214144769-640e2888-4982-4580-94dc-8d3aea3469bc.png">

... some funders need to do multiple or more complex searches. There are more than 57 datasets containing data created from NIH-funded research, but only 57 have the text "NIH" in the Funding Information Agency field.

During the GREI training workshops on Jan 24 and 25, we'll have a chance to learn about funders' experiences with finding data from the research they fund. And I plan to review this new javascript with users in the repository who often add funding metadata to their datasets.

**Comment by jggautier** [comment]
We'll eventually want to send this metadata to DataCite, so I took a look at the funding metadata that's already included in the the OpenAIRE export (the OpenAIRE schema is based on the DataCite schema) and I looked at examples that DataCite provides for sending funding metadata.

**How funding metadata is included in Dataverse's OpenAIRE export**:

```
<fundingReferences>
	<fundingReference>
		<funderName>Contributor: Funder</funderName>
	</fundingReference>
	<fundingReference>
		<funderName>Grant Agency1</funderName>
		<awardNumber>Grant Number1</awardNumber>
	</fundingReference>
	<fundingReference>
		<funderName>Grant Agency2</funderName>
		<awardNumber>Grant Number2</awardNumber>
	</fundingReference>
</fundingReferences>
```

The first fundingReference property contains the name entered in the Contributor field when Contributor Type "Funder" is chosen. I'm hoping we can fix that as part of another issue (https://github.com/IQSS/dataverse/issues/4859). So let's ignore that for now.

The next two fundingReference properties show the funder name entered in the Funding Information Agency field and award number entered in the Funding Information Identifier field.

**Sending funder identifier metadata to DataCite**

To add the funder identifier, which the javascript would grab from the Crossref API when a depositor chooses a funder from the suggested list, we could use DataCite's funderIdentifier property from [their example XML](https://schema.datacite.org/meta/kernel-4.4/example/datacite-example-fundingReference-v4.xml):

`<funderIdentifier funderIdentifierType="Crossref Funder ID">https://doi.org/10.13039/5011</funderIdentifier>`

So when depositors entered a funding name and award number, what's sent to DataCite (and included in the OpenAIRE export) would look like this:

```
<fundingReferences>
	<fundingReference>
		<funderName>Grant Agency1</funderName>
		<awardNumber>Grant Number1</awardNumber>
		<funderIdentifier funderIdentifierType="Crossref Funder ID">https://doi.org/10.13039/5011</funderIdentifier>
	</fundingReference>
</fundingReferences>
```

This suggests that DataCite prefers the DOI, such as http://dx.doi.org/10.13039/100000001, instead of the ID number 100000001.

And funderIdentifierType is required, so Dataverse will need to know that if the depositor chooses a funder from the javascript's suggested list, the funder identifier is a Crossref Funder ID, that that it can include that in the funderIdentifierType attribute.

**Comment by mreekie** [comment]
resizing for next sprint:
- Have discovered there is a lot of unknowns and work associated with doing this ofr the firs time.
- This will be for test. It won't be for produciton.
- This is really answering the ui/ux that we want, although its' in test.
- Likely to be done in the same way jim described storing the orcid ID.
- Sizing it at: 80

**Comment by pdurbin** [comment]
I've been bad about leaving updates here. It's early days for me getting this working. I've switch trying to understand the ROR code to trying to understand the creator and skosmos code. I'm too embarrassed to push a branch of my hacking to the main external vocab repo so I just forked it to "pdurbin" and put it here: https://github.com/pdurbin/dataverse-external-vocab-support/commit/c8fb9c28a452b256fc90d8d043d7012656b04849 (That said, it's mostly the same code just with comments and such, some config, some experiements.)

I said this a couple times but I'm ok with another developer taking on this issue if they want. It's potentially fun but there's a lot to do. I mostly picked it up because we want to make progress on the NIH stuff and there wasn't much left toward the end of the last sprint.

**Comment by pdurbin** [comment]
Decent progress today. I pushed another scratch commit: https://github.com/pdurbin/dataverse-external-vocab-support/commit/35d4eac

The code is now somewhat demo-able and I put it on https://dev1.dataverse.org in preparation for tomorrow's meeting.

In case the demo gods are not with me, below are some screenshots as well.

![Screen Shot 2023-01-30 at 4 23 32 PM](https://user-images.githubusercontent.com/21006/215599269-ca0520f8-97df-40b6-9c4f-7e941ac518a0.png)
![Screen Shot 2023-01-30 at 4 23 41 PM](https://user-images.githubusercontent.com/21006/215599270-837eed61-959a-47bc-90db-9e2b452a0484.png)
![Screen Shot 2023-01-30 at 4 23 54 PM](https://user-images.githubusercontent.com/21006/215599271-d00e3b37-294b-468a-bb46-a827cf38fd86.png)
![Screen Shot 2023-01-30 at 4 24 00 PM](https://user-images.githubusercontent.com/21006/215599274-afe09c25-99a8-4ae5-8cfc-a1cb01a3ac69.png)
![Screen Shot 2023-01-30 at 4 24 07 PM](https://user-images.githubusercontent.com/21006/215599276-9fa5cfc1-8753-4ca2-a565-09695426a517.png)
![Screen Shot 2023-01-30 at 4 25 06 PM](https://user-images.githubusercontent.com/21006/215599277-cafab8ad-4ccf-4881-8d71-d2080a048ed0.png)
![Screen Shot 2023-01-30 at 4 25 37 PM](https://user-images.githubusercontent.com/21006/215599282-03707b2f-16e0-4f22-bb15-9fd430c4afbc.png)
![Screen Shot 2023-01-30 at 4 26 08 PM](https://user-images.githubusercontent.com/21006/215599283-baf2e978-9a45-4b56-aa9a-b00379c7d6d2.png)
![Screen Shot 2023-01-30 at 4 26 48 PM](https://user-images.githubusercontent.com/21006/215599285-ea1f158d-986f-46aa-8985-c914b5069ab1.png)
![Screen Shot 2023-01-30 at 4 27 11 PM](https://user-images.githubusercontent.com/21006/215599287-7d756177-492a-45f0-b191-c0246f6c22c1.png)

**Comment by pdurbin** [comment]
After standup we talked through the screenshots above and I did a demo. We decided to store the funder PID URL (e.g. http://dx.doi.org/10.13039/100000002) where we've been putting the string for the funder's name (e.g. NIH), when we can. This is highlighted in red below. From https://design.penpot.app/#/view/2ca7d284-ea89-8144-8001-fd5447dbc79e?page-id=2ca7d284-ea89-8144-8001-fd5447dbc79f&section=interactions&index=0&share-id=e666624f-1b00-80b5-8001-fd5638e43b73

<img width="686" alt="Screen Shot 2023-01-31 at 5 43 32 PM" src="https://user-images.githubusercontent.com/21006/215900819-8f83384e-8f6c-49b6-a802-93d61cda0388.png">

**Comment by mreekie** [comment]
Review for monthly 

Bump: @pdurbin @jggautier 
- Thank  you 1000X for the discussion and comments captured to this issue!
- I thought someone mentioned that the Fundref name is now changed? Can you remind me?
- I'm working on the monthly update and want to be sure I understand what will come out of this issue.

Here's my shot:

We are exploring the use of a similar methodology to a script authored by the GDCC that retrieves ROR/Author Affiliation to retrieve the Agency and Agency identifier from the fundref registry. At the end we will have a demoable UI.  This will be used to collect user feedback to identify use cases (e.g during the GREI training workshops on Jan 24 and 25)

**Comment by mreekie** [comment]
Bump: @pdurbin @jggautier
 - I went through the meeting notes and ended up with a bit more on the update

**Comment by mreekie** [comment]
Sprint resizing

There are 2 streams of work:
- JSON export 
- API related issues
- There continues to be a lot of uncertainty around the details, so discovery still happening.
- Probably some more follow-up with Julian to nail down the scope/definition of done.
- no change in sizing for new sprint

**Comment by jggautier** [comment]
Thought I'd try summarizing some the uncertainty as I understand it:

- **Results from the API can be pretty poor** (like @pdurbin's said)
  This is just based on searches of well known funding agencies and this can make the suggestions less useful. When you type in National Science Foundation or NIH, what we expect isn't at the top of the results. The order of the results is exactly the order in the JSON document that's returned. I'm not sure what that order is, but it's not using guidelines for prioritizing more relevant results (such as prioritizing whole-word matches and matches in certain fields like name instead of alternative name).

  I don't know if it's possible to make the API return results that are sorted by relevance. I tried some of the parameters of the API (documented at https://github.com/CrossRef/rest-api-doc) and there's a sort by relevance/score parameter, but when I try it on the `https://api.crossref.org/funders`, e.g. https://api.crossref.org/funders?query=NIH&sort=score, I get errors that I think says that sorting by relevance isn't supported when searching for funders. The parameter does work when searching for "works", e.g. https://api.crossref.org/works?query=R34MH115769&sort=score.

  @pdurbin have you played around with this? If it's possible to have the API sort funder results by relevance, is this useful for this javascript? Should we reach out to Crossref to ask if it's currently possible to get the API to sort funders in the results by relevance?

- **Funder name can't be searched on**
  When I looked at the functionality on https://dev1.dataverse.org today, it seemed like the PID (DOI) of the funder is indexed and so it can be searched on, but the funder name isn't indexed. There's a dataset on that test server with _National Institutes of Health_ in the Funding Information Agency field, but when I search for National Institutes of Health, that dataset isn't returned. And when I search for it with quotes, "National Institutes of Health", nothing is returned.

  This will affect how findable those datasets are when people search by funder name, which I suspect they'll do more often than they search by PID.

- **Display issue after choosing funder from suggestions**
  When I choose from the list of suggested funders, there's a UI display issue that @pdurbin's already mentioned (and might have already fixed?)

@mreekie you wrote in the first comment that the definition of done includes "Code, javascript and a test metadatablock in the other repo". That's so that we can evaluate it right? I've been writing that I plan to test it with users (particularly users who often add funding metadata to their datasets). But I think right now we're trying to resolve what we know would be issues if this was tested with users right now.

**Comment by qqmyers** [comment]
FWIW: Names should appear if there is a facet and in advanced search. These, and I think basic search as well, depend on the expandedValue that @pdurbin hasn't yet completed. Once that's done, I think these will be findable even by any i18n names they have.

**Comment by jggautier** [comment]
Thanks @qqmyers. Then I'll hold off on reviewing, asking more questions.

**Comment by pdurbin** [comment]
I unassigned myself and haven't been actively working on this. Anyone else is welcome to pick it up. I'm happy to give a brain dump.

Some scratch work on the Dataverse side: https://github.com/pdurbin/dataverse/commit/ba4575a

Some scratch work on the external vocab side: https://github.com/gdcc/dataverse-external-vocab-support/compare/main...pdurbin:dataverse-external-vocab-support:scratch3

**Comment by qqmyers** [comment]
With #9402 and https://github.com/gdcc/dataverse-external-vocab-support/pull/14 , there's basic support for using the CrossRef funder registry with the grantNumberAgency field and the Research Organization Registry with the authorAffiliation field. As is, they work ~ like the original ORCID script allowing selection from a list of choices and displaying that choice correctly in the various parts of the display (see#9150), and capture/provide additional info in the Json and OAI-ORE exports.  Both sort results to prioritize entries where the entry is 'active' (ROR only), where typed text matches the acronym or relevant tokens (fundreg only), and, lastly if the entry has been used by that user before. This means that NIH appears near the top in both fields to start and, once the user has selected the real NIH entry once, it is always at the top. (Same if the once select a bad one, until they delete the browser's localStore cache.) Values are truncated to fit the narrow inputs allowed for child fields. The fundreg script sends a mailto: address so that CrossRef will the requests on their priority queue. Both use cached values rather than pinging the services every time a term is displayed.

That said, there are a variety of issues that could be addressed now or later:

- There is no internationalization - something similar to what was done for the previewers could be added (possibly to the cvocutils.js script)
- The ROR search for NIH can still be confusing since there are several orgs with that acronym. The real NIH could be prioritized  in a couple ways:
  - pre-cache the NIH and any other important entries so that sort will prioritize them
  - inspect the response from ROR and see if other fields would allow a better sort (possibly location based sort?) - this is constrained by what ROR provides.
- The current widget is not responsive and doesn't shrink/grow well with page size changes. This might be improvable via css although I've seen some limitations to the select2 widget itself in terms of it hardcoding width as it is launched (based on querying it's current parent). An alternative would perhaps be to switch to the pop-up concept used in the original (non-working) ror script. The main display then only includes a button to launch the widget and the widget can then be sized independent of the size of the underlying input space on the Dataverse page.
- The current scripts do not make the entries links out to external web information. For fundreg, the main issue is that there is no info about a web page for the org, just links to the raw json information in the registry (which is ugly/confusing). For ROR, there are optional fields that could be used - "links" seems to usually have one entry to the org homepage. There is also an optional wikipedia link that could be used. If someone can propose a concrete algorithm (i.e. use the first "links" entry if it exists, use the wikipedia link if that exists and links is empty, and if there is no entry in either, don't make a link) then it should be relatively easy to implement (though the example here means that some ROR entries won't be linked and others will which could be confusing).
- I have not checked a11y - there isn't much styling that isn't inherited from Dataverse, so I expect these scripts are probably OK.
- Fundreg can be slow and did give a 504/gateway timeout during my testing at one point. This hopefully won't occur often, but would result in the raw id number showing if the user had never cached the entry before. As noted, I did do what Fundreg requests to get improved performance. Their next suggestion is basically to run your own copy of the api instead which could be done if this becomes a real issue. (By contrast, ROR seems to be very quick.)

**Comment by mreekie** [comment]
Daily
- Sounds like the plan is to get through what Jim has done for a PR.
- Do a demo for Sonia for appropriateness. If what we have is enough then close this.
- Then revisit what's left as separate issues.
