### ISSUE TITLE
 NcML previewer doesn't work with drafts

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9416]
Currently we get this error:

"Unable to retrieve NcML file. Please try again. The most common issue is that your login has timed out. If the problem persists, please contact the support team of this data repository. Please include any status code included at the end of this message: Forbidden"

![221693399-e18ececd-197e-431f-b130-7eafb405f900](https://user-images.githubusercontent.com/21006/221956396-9f6bbccf-e2c3-41cb-9088-11c32c0199b1.png)

We should update ncml.js to handle API tokens (like other previewers)

Please note: this issue is only for tracking. The work will be done in a gdcc repo:

- https://github.com/gdcc/dataverse-previewers/issues/25

**Comment by pdurbin** [comment]
Still no luck. I'm sure it's a real bug. I can reproduce it on demo and prod.

However, I can't reproduce this on my laptop or my dev1 server. It just works in both places.

Here's dev1, for example, happily returning the NcML file:

![Screen Shot 2023-05-16 at 5 22 00 PM](https://github.com/IQSS/dataverse/assets/21006/357fc193-fee5-47dc-afef-ed42d4b5b92c)

I'm not sure why it's working in my browser like that for dev1 (and my laptop). As expected when I try to curl the file from the command line it fails:

`$ curl https://dev1.dataverse.org/api/access/datafile/1073/auxiliary/NcML/0.1`
`{"status":"ERROR","code":403,"message":"Not authorized to access this object via this API endpoint. Please check your code for typos, or consult our API guide at http://guides.dataverse.org.","requestUrl":"https://dev1.dataverse.org/api/v1/access/datafile/1073/auxiliary/NcML/0.1","requestMethod":"GET"}`

**Comment by qqmyers** [comment]
Did it get fixed? - See https://github.com/gdcc/dataverse-previewers/pull/30#issuecomment-1540707492 - sounds like it was fixed in source but not yet built at that point.

**Comment by pdurbin** [comment]
@qqmyers thanks but no I believe that's Jan pre-emptively fixing the H5Web previewer.

**Comment by qqmyers** [comment]
Sorry - my bad. You don't have the cookie feature flag on or something?

**Comment by pdurbin** [comment]
I'm still not sure why I don't see this problem when I serve up previewers from the same server as Dataverse but I was able to replicate it my pointing Dataverse on my laptop to previewers hosted on my dev1 server.

I'm putting this into "ready for review". The pull request is here:

- https://github.com/gdcc/dataverse-previewers/pull/32

**Comment by pdurbin** [comment]
We just discussed this during the retrospective. I gave it as an example of an item that has been sitting in "Ready for Review" for over a month.

Since @qqmyers already approved the PR (thanks! https://github.com/gdcc/dataverse-previewers/pull/32#pullrequestreview-1482326465 ), we decided this can go to "Ready for QA" so I moved it. Thanks, all!
